mysql:
  dbHost: "localhost"
  dbPort: 3306 
  dbUser: root
  dbPassword: "Fabric@2024"
  dbName: fabric

jwtkey: 0123456789
APIKey: 11287629-5941-41e1-bb3b-50bfad7cf422
huawei:
  obs:
    access_key_id: 11287629-5941-41e1-bb3b-50bfad7cf422
    secret_access_key: GD4iFCG8nezLvRCkjnyUSEpCVUEGD30DB1ufuj47