-- 为user表添加必要字段
#ALTER TABLE user ADD COLUMN IF NOT EXISTS id INT AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE user ADD COLUMN IF NOT EXISTS registration_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user ADD COLUMN  last_active_time DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user ADD COLUMN IF NOT EXISTS user_level INT DEFAULT 0;
ALTER TABLE user ADD COLUMN location VARCHAR(255) DEFAULT '未知地点';
#ALTER TABLE user ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8) DEFAULT NULL;
#ALTER TABLE user ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8) DEFAULT NULL;

-- 为item表添加必要字段
ALTER TABLE item ADD COLUMN  category VARCHAR(50) DEFAULT '其他';
ALTER TABLE item ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE item ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

-- 创建分类表
CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

-- 创建交易表
CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT NOT NULL,
    seller_id INT NOT NULL,
    buyer_id INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    transaction_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    location VARCHAR(255) DEFAULT '未知地点',
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (seller_id) REFERENCES user(id),
    FOREIGN KEY (buyer_id) REFERENCES user(id)
);

-- 创建用户活动表
CREATE TABLE IF NOT EXISTS user_activities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    activity_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
